name: Workflow with Independent Jobs

on:
  workflow_dispatch:
    inputs:
      branchAndRequest:
        description: 'Input format: branchname|RequestID'
        required: true
      UI_Deployment:
        description: 'Check to enable UI Deployment'
        type: boolean
        default: false
      run-step-1:
        description: 'Run Step 1?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  step-1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run-step-1 == 'true' }}
    steps:
      - name: Step 1 - Conditional Execution
        run: |
           echo "Step 1: Running because condition is true."

  step-2:
    runs-on: ubuntu-latest
    needs: [step-1]
    if: ${{ always() }}
    steps:
      - name: Step 2 - Processing
        if: ${{ github.event.inputs.run-step-1 == 'false' || needs.step-1.result == 'success' }}
        run: |
           echo "Step 2: Processing data."

  step-3:
    runs-on: ubuntu-latest
    needs: [step-2]
    if: ${{ needs.step-2.outcome == 'success' }}
    steps:
      - name: Step 3 - Validating
        run: |
           echo "Step 3: Validation successful."

  step-4:
    runs-on: ubuntu-latest
    needs: [step-3]
    if: ${{ needs.step-3.result == 'success' }}
    steps:
      - name: Step 4 - Finalizing
        run: |
           echo "Step 4: Finalization complete."
