name: Workflow with Independent Jobs

on:
  workflow_dispatch:
    inputs:
      branchAndRequest:
        description: 'Input format: branchname|RequestID'
        required: true
      UI_Deployment:
        description: 'Check to enable UI Deployment'
        type: boolean
        default: false
      run-step-1:
        description: 'Run Step 1?'
        required: true
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  step-1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.run-step-1 == 'true' }}
    steps:
      - name: Step 1 - Conditional Execution
        run: |
           echo "Step 1: Running because condition is true."

  step-2:
    runs-on: ubuntu-latest
    needs: [step-1]
    if: ${{ always() }}
    steps:
      - name: Step 2 - Processing
        if: ${{ github.event.inputs.run-step-1 == 'false' || needs.step-1.result == 'success' }}
        run: |
           echo "Step 2: Processing data."

  trigger-workflow2:
    needs: step-2
    uses: repo2-owner/repo2-name/.github/workflows/scan.yml@main
    with:
      input1: "value1"            # Replace with actual input value
      input2: "value2"            # Replace with actual input value
    secrets:
      secret_key: "SecretValue"  # Ensure this secret exists in Repo1

  continue-after-success:
    needs: trigger-workflow2
    runs-on: ubuntu-latest
    if: ${{ needs.trigger-workflow2.result == 'success' }}
    steps:
      - name: Success Message
        run: echo "Workflow 2 executed successfully. Continuing Workflow 1."
